bourse_homepage:
    path:     /hello/{name}
    defaults: { _controller: BourseBundle:Default:index }
bourse_profile:
    path:     /profile
    defaults: { _controller: BourseBundle:Profile:index }
bourse_1337:
    path:     /1337
    defaults: { _controller: BourseBundle:Default:accueil }
bourse_tableau:
    path:     /TableauDeBord
    defaults: { _controller: BourseBundle:Profile:index }

bourse_connexion:
    path: /connection
    defaults: { _controller: BourseBundle:Profile:connection }
bourse_inscription:
    path: /validerinscription
    defaults: { _controller: BourseBundle:Profile:validerinscription }

bourse_inscrire:
    path: /inscription
    defaults: { _controller: BourseBundle:Profile:inscrire }

bourse_deconnexion:
    path: /deconnection
    defaults: { _controller: BourseBundle:Profile:Deconnection }

bourse_entreprise:
    path: /entreprise/{ticker}
    defaults: { _controller: BourseBundle:Entreprise:voirEntreprise}

bourse_recherche:
    path: /recherche
    defaults: { _controller: BourseBundle:Entreprise:rechercher}

bourse_analyse:
    path: /analyse
    defaults: { _controller: BourseBundle:Profile:analyse}

    defaults: { _controller: BourseBundle:Entreprise:rechercher}
generer_secteurs:
    path: /secteurs
    defaults: { _controller: BourseBundle:Entreprise:secteurs}

bourse_gererTableau:
    path: /gererTableau
    defaults: { _controller: BourseBundle:Profile:gererTableau}

bourse_favoris:
    path: /favoris
    defaults: { _controller: BourseBundle:Profile:favoris}

